---
- name: Set facts for Debian/Ubuntu
  ansible.builtin.set_fact:
    tmux_pkgs:
      - tmux
      - powerline
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Set facts for Fedora
  ansible.builtin.set_fact:
    tmux_pkgs:
      - tmux
      - powerline
      - tmux-powerline
  when: ansible_distribution == "Fedora"

- name: Install packages
  become: true
  ansible.builtin.package:
    name: "{{ tmux_pkgs }}"
    state: present

- name: Generate system-wide tmux config
  become: true
  ansible.builtin.template:
    src: tmux.conf.j2
    dest: /etc/tmux.conf
    owner: root
    group: root
    mode: "0644"

- name: Ensure tmux powerline config directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_items:
    - /etc/xdg/powerline/colorschemes/tmux
    - /etc/xdg/powerline/themes/tmux

- name: Copy powerline config
  become: true
  ansible.builtin.copy:
    src: powerline_config.json
    dest: /etc/xdg/powerline/config.json
    owner: root
    group: root
    mode: "0644"

- name: Copy tmux powerline config
  become: true
  ansible.builtin.copy:
    src: powerline_tmux_vsos.json
    dest: /etc/xdg/powerline/themes/tmux/vsos.json
    owner: root
    group: root
    mode: "0644"

- name: Copy tmux powerline colorscheme
  become: true
  ansible.builtin.copy:
    src: powerline_color_tmux_vsos.json
    dest: /etc/xdg/powerline/colorschemes/tmux/vsos.json
    owner: root
    group: root
    mode: "0644"
